(fix) Only try to update plugins when there is plugins to update.
We were using pop on a list but this list can be empty.

2023-11-10 11:35:20,357 - ERROR -
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_registeryagent.py", line 294, in action
    getattr(xmppobject, function_plugin)(msg, data)
  File "/usr/lib/python2.7/dist-packages/pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_loadpluginlistversion.py", line 203, in plugin_loadpluginlistversion
    self.remoteinstallPlugin()
  File "/usr/lib/python2.7/dist-packages/pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_loadpluginlistversion.py", line 130, in remoteinstallPlugin
    plugmachine = self.file_deploy_plugin.pop(0)
IndexError: pop from empty list

We fixes this backtrace.