(AGENT) Missing attribute in MUCBot - Add atribute time_before_reinscription
Traceback (most recent call last):
  File "C:\Program Files\Python3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\Python3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python3\Lib\site-packages\pulse_xmpp_agent\agentxmpp.py", line 4280, in __init__
    xmpp = MUCBot(
           ^^^^^^^
  File "C:\Program Files\Python3\Lib\site-packages\pulse_xmpp_agent\agentxmpp.py", line 706, in __init__
    self.time_before_reinscription,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MUCBot' object has no attribute 'time_before_reinscription'