[plugin resultinventory] Handle KeyError exception
When fusioninventory is not correctly installed/started it does not send
an inventory hence this backtrace.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_resultinventory.py", line 66, in action
    inventory = zlib.decompress(base64.b64decode(data['inventory']))
KeyError: 'inventory'

We now add a more userfriendly error message.