[monitoring] Initialise graph for machine (#97)
* [substitut registery] reg expression for blacklist

* [deployement avanced] restart deploy after pause.

* [Quick deployement] delay install after transfert package for Quick Deployment

* [deployment ARS] adaptation syncthing separate

* [deployment ARS] adaptation syncthing separate

* [deployment ARS] adaptation syncthing separate

* [Fixe plugin inventory] old inventory is save in temp

* [fixe syncthing agent machine and relay] search deviceid syncthing for registration. before initialisation of syncthing.

* [registration plugin substitute] elimination macadresse blacklist as soon as possible

* [geolocalisation] refactoring geolocalisation generator.

* [geolocalisation] refactoring geolocalisation generator.

* [QA] use None instead of none

* [Fix] Fix ident

* [deployement syncthing] adress configuration device pulse on relayserver.
parametre add : syncthing_port,syncthing_gui_port,syncthing_home,syncthing_share

* [syncthing deployement] add parameter ARS port syncthing for configuration device on machine.

* [fix syncthing deployement] add parameter ARS port syncthing for configuration device on machine

* [fixe syncthing] Correct typos or other apparent mistakes.

* [fix syncthing deployement] fixe scan_syncthing_deploy

* [QA] Remove commented code for the previous commit

* [deployement alternate package] fix change folder

* [fix deployement syncthing] search device id for ARS pulse

* [feature deployement syncthing] add infrormation syncthing in table relayserver

* [feature deployement syncthing] add folder sharing on each machine from cluster ars.

* [Fixe deployement] list uniq mac adres

* [fixe regexp mysql] deployement

* [registration migration] clean old jid

* [fixe deployement] update status deployement

* [dymgroup peripheral] extend xmp inventory with file extern

* utils.py: Fix pep8 errors

* [EX10] #250: EX10: Enregistrer les status Online/Offline et leur durée et les afficher

* [EX10]  # 250 chang name fild table uptime_machine

* [EX10]  # 250 add stat function on uptime_machine/lastday

* [EX11 Déploiement sur URL] #251: Déploiement sur URL  (add step download file in grafcetdeply)

* [EX11 Déploiement sur URL] #251: Déploiement sur URL  (add step download file in grafcetdeply)

* [EX11 Déploiement sur URL] #251: Déploiement sur URL  (fix message)

* [geolocalisation] Add timeout of 5 while fetching info from geolocalisation servers

* [EX02 monitoring] issu #253  send msg from server kiok from monitoring

* [EX02 monitoring] issu #253  add function minifyjsonstringrecv. accept comment in json and a fews errors format json

* [feature] add fonction check json string minifyjsonstring

* [EX02 monitoring] issu #253  add gestion tablesmonitoring

* [EX02 monitoring] issu #253  add parameter path file monitoring conf

* [EX02 monitoring] issu #253  add plugin update monitoring file configuration

* [fixe EX02 monitoring] issu #253 no update file monitoring config for ARS

* [fixe EX02 monitoring] issu #253 add table for initialisation graph by machine

* [deployment] Fix download of file from URL

* [EX11 Déploiement sur URL] #251: Déploiement sur URL  (add step download file in grafcetdeply)

(cherry picked from commit 5387cea28dd85e0ab3bbb0e64eac913f05d2be06)

* [EX11 Déploiement sur URL] #251: Déploiement sur URL  (fix message)

(cherry picked from commit b4190a5e38a06762258617f560274d693cd968c8)

* [EX11 Déploiement sur URL] #251: Déploiement sur URL  (fix message)

(cherry picked from commit 7e6c55393860acd2c1e1f1c2dedd1753dc6bb5ca)

* Fix pep8 errors

* Fix pep8 errors

* ignore FLK-E722 issue for this except
In fact here we want to catch all exceptions.

* Fix style and typos

* [deployment] Fix download of file from URL
fixes pulse-project/siveo-todo#251

Co-authored-by: jfk <jean-francois.kneib@siveo.net>
Co-authored-by: Nicolas Lécureuil <neoclust@mageia.org>

* [installer] Remove profile using powershell command and warn user if the deletion failed

* Update fusioninventory to version 2.5.2

* [plugin resultinventory] Handle KeyError exception

When fusioninventory is not correctly installed/started it does not send
an inventory hence this backtrace.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulse_xmpp_master_substitute/pluginsmastersubstitute/plugin_resultinventory.py", line 66, in action
    inventory = zlib.decompress(base64.b64decode(data['inventory']))
KeyError: 'inventory'

We now add a more userfriendly error message.

* [monitoring] Create Online-Offline Status panel and dashboard for machines when they get online (#92)

* [fixe localisation] fix creation object geodata

* #250: EX10: Enregistrer les status Online/Offline et leur durée et les afficher

* # 250 chang name fild table uptime_machine

* Fix pep8 errors

* Add documentation ( start )

* Fix pep8 errors

* # 250 add stat function on uptime_machine/lastday

* Fix pep8 errors

* Fix pep8 errors

* Add documentation

* [status history] Fix description of function
fixes pulse-project/siveo-todo#250

* [monitoring] Create Online-Offline Status panel and dashboard for machines when they get online
fixes pulse-project/siveo-todo#250

* Fix indent

* Fix indent

Co-authored-by: jfk <jean-francois.kneib@siveo.net>
Co-authored-by: Nicolas Lécureuil <neoclust@mageia.org>

* Upgrate pycurl version

* Revert "Upgrate pycurl version"

This reverts commit fe5829681d0d0834b08cabe354b68d0d811ca58c.

* [mac] Update pycurl version to 7.43.0.5 in macOS

* Update plyvel version

* Update plyvel version

* [mac] Do not install curl directly
New Brew does not accept install arguments.

* [monitoring] Review plugins pep8 and english language typos
fixes pulse-project/siveo-todo#253

* [monitoring] Review pep8 and english language typos
fixes pulse-project/siveo-todo#253

* [monitoring] review english texts
fixes pulse-project/siveo-todo#253

* [fixe EX02 monitoring] issu #253 initialisation graph by machine

* [EX02 monitoring] issu #253  monitoring add plugin vectormonitoringagent

* [fixe inventory pluging]

* [fixe plugin substitute get session deploy]

* Update plugins versions

* [monitoring] Review vectormonitoring plugin english language typos
fixes pulse-project/siveo-todo#253

* [inventory] Fix typo

Co-authored-by: jfk <jean-francois.kneib@siveo.net>
Co-authored-by: Nicolas Lécureuil <neoclust@mageia.org>