(FIX) Ensure Byte Encoding in remotexmppmonitoring - Verify and convert 'result' to bytes before compression
2023-11-11 21:15:34,706 - ERROR - (AG_EVENT)_custom_xep_get : error command : a bytes-like object is required, not 'str'
2023-11-11 21:15:34,706 - ERROR - (AG_EVENT)
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\pulse_xmpp_agent\agentxmpp.py", line 1024, in _custom_xep_get
    result = dispach_iq_command(self, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pulse_xmpp_agent\lib\xmppiq.py", line 86, in dispach_iq_command
    result = callXmppFunctionIq(data["action"], xmppobject=xmppobject, data=data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pulse_xmpp_agent\lib\xmppiq.py", line 59, in callXmppFunctionIq
    return getattr(functionsynchroxmpp, functionname)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pulse_xmpp_agent\lib\xmppiq.py", line 508, in remotexmppmonitoring
    result = base64.b64encode(zlib.compress(result, 9))
                              ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'